In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [20]:
target = df.target
df = df.drop('target', axis = 'columns')

In [21]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2         0   0     3  
3         2   1     3  
4         1   3     2  
...     ...  ..   ...  
1020      2   0     2  
1021      1   1     3  
1022      1   1     2  
1023      2   0     2  
1024      1   1     3  

[1025 rows x 13 columns]

In [22]:
target

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

DataSet for PCA

In [40]:
X = df
y = target

In [41]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-0.26843658,  0.66150409, -0.91575542, ...,  0.99543334,
         1.20922066,  1.08985168],
       [-0.15815703,  0.66150409, -0.91575542, ..., -2.24367514,
        -0.73197147,  1.08985168],
       [ 1.71659547,  0.66150409, -0.91575542, ..., -2.24367514,
        -0.73197147,  1.08985168],
       ...,
       [-0.81983438,  0.66150409, -0.91575542, ..., -0.6241209 ,
         0.23862459, -0.52212231],
       [-0.4889957 , -1.51170646, -0.91575542, ...,  0.99543334,
        -0.73197147, -0.52212231],
       [-0.04787747,  0.66150409, -0.91575542, ..., -0.6241209 ,
         0.23862459,  1.08985168]])

In [42]:
from sklearn.model_selection import train_test_split
x_train_scaled, x_test_scaled, y_train_scaled, y_test_scaled = train_test_split(X_scaled, y, train_size = 0.2)

In [43]:
x_train_scaled

array([[ 1.27547724, -1.51170646, -0.91575542, ..., -0.6241209 ,
         1.20922066,  1.08985168],
       [ 0.28296121, -1.51170646,  0.05593123, ..., -0.6241209 ,
         0.23862459, -0.52212231],
       [ 0.39324077,  0.66150409,  0.05593123, ..., -0.6241209 ,
        -0.73197147, -0.52212231],
       ...,
       [ 0.61379988, -1.51170646,  1.02761788, ...,  0.99543334,
        -0.73197147, -0.52212231],
       [ 1.27547724, -1.51170646,  1.02761788, ..., -0.6241209 ,
         0.23862459, -0.52212231],
       [-0.59927526,  0.66150409,  1.02761788, ..., -0.6241209 ,
         2.17981673,  1.08985168]])

In [44]:
x_test_scaled

array([[ 0.17268165,  0.66150409,  1.99930453, ..., -0.6241209 ,
        -0.73197147,  1.08985168],
       [-1.26095261,  0.66150409, -0.91575542, ..., -0.6241209 ,
        -0.73197147, -0.52212231],
       [ 1.38575679, -1.51170646, -0.91575542, ...,  0.99543334,
         1.20922066, -0.52212231],
       ...,
       [-0.59927526, -1.51170646, -0.91575542, ...,  0.99543334,
        -0.73197147, -0.52212231],
       [ 0.94463856, -1.51170646,  0.05593123, ...,  0.99543334,
         1.20922066, -0.52212231],
       [-0.59927526,  0.66150409,  1.02761788, ...,  0.99543334,
         2.17981673, -0.52212231]])

# Building a Model using Linear Regression without PCA

DataSet for Non-PCA

In [30]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df, target, test_size = 0.2)

In [45]:
x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
55     55    1   0       140   217    0        1      111      1      5.6   
167    57    0   0       120   354    0        1      163      1      0.6   
251    45    0   1       112   160    0        1      138      0      0.0   
939    49    0   1       134   271    0        1      162      0      0.0   
534    54    0   2       108   267    0        0      167      0      0.0   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
220    57    0   1       130   236    0        0      174      0      0.0   
160    77    1   0       125   304    0        0      162      1      0.0   
1022   47    1   0       110   275    0        0      118      1      1.0   
843    59    1   3       160   273    0        0      125      0      0.0   
448    51    0   2       120   295    0        0      157      0      0.6   

      slope  ca  thal  
55        0   0     3  
167       2   0     2  
251       1   0     2  
939       1   0     2  
534       2   0     2  
...     ...  ..   ...  
220       1   1     2  
160       2   3     2  
1022      1   1     2  
843       2   0     2  
448       2   0     2  

[820 rows x 13 columns]

In [46]:
x_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
965   76    0   2       140   197    0        2      116      0      1.1   
26    44    1   2       130   233    0        1      179      1      0.4   
276   57    1   0       132   207    0        1      168      1      0.0   
467   47    1   0       110   275    0        0      118      1      1.0   
805   53    1   0       142   226    0        0      111      1      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
399   63    1   3       145   233    1        0      150      0      2.3   
64    29    1   1       130   204    0        0      202      0      0.0   
755   48    1   2       124   255    1        1      175      0      0.0   
322   45    1   0       142   309    0        0      147      1      0.0   
321   48    0   2       130   275    0        1      139      0      0.2   

     slope  ca  thal  
965      1   0     2  
26       2   0     2  
276      2   0     3  
467      1   1     2  
805      2   0     3  
..     ...  ..   ...  
399      0   0     1  
64       2   0     2  
755      2   2     2  
322      1   3     3  
321      2   0     2  

[205 rows x 13 columns]

In [31]:
lr.fit(x_train, y_train)

LinearRegression()

In [32]:
lr.score(x_test, y_test)

0.38194321220907335

# Building a Model using Linear Regression with PCA

In [47]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
X_pca = pca.fit_transform(X)

In [48]:
x_train_pca, x_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca, y, test_size=0.2)

In [49]:
from sklearn.linear_model import LinearRegression
lr_pca = LinearRegression()
lr_pca.fit(x_train_pca, y_train_pca)
lr_pca.score(x_test_pca, y_test_pca)

0.24258280749618688

# Building a Model using Logistic Regression without PCA

In [34]:
from sklearn.linear_model import LogisticRegression
logi = LogisticRegression()
logi.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [37]:
logi.score(x_test, y_test)

0.7902439024390244

# Building a Model using Logistic Regression with PCA

In [50]:
logi_pca = LogisticRegression()
logi_pca.fit(x_train_pca, y_train_pca)
logi_pca.score(x_test_pca, y_test_pca)

0.7365853658536585

# Building a Model using Random Forest Classifier without PCA

In [38]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 40)
rfc.fit(x_train, y_train)

RandomForestClassifier(n_estimators=40)

In [39]:
rfc.score(x_test, y_test)

0.9707317073170731

# Building a Model using Random Forest Classifier with PCA

In [51]:
rfc_pca = RandomForestClassifier(n_estimators = 40)
rfc_pca.fit(x_train_pca, y_train_pca)
rfc_pca.score(x_test_pca, y_test_pca)

1.0